### PR TITLE
New configs, metadata, trufflehog3 plugin features

### PR DESCRIPTION
**Pull request by shikari-ac**
This PR introduces a standardized default configuration for the Trufflehog3 scanner, adds new options for managing the .trufflehog3.yml file, updates Scanio metadata naming conventions, enhances the HTTP client with custom headers and environment variable support, and implements report transformation with deduplication for Trufflehog3 scans.

## Default Configuration for Trufflehog3 Scanner
To provide a standardized baseline configuration that excludes common directories and files that are not relevant to the scan.
The default configuration includes exclusion rules for:
- 3rd-party dependencies: Excludes vendor and node_modules directories.
- Go lock files: Excludes go.mod and go.sum.
- JavaScript lock files: Excludes package.json and package-lock.json.
- Python lock files: Excludes Pipfile.lock.
- PHP lock files: Excludes composer.lock.
- Git subproject commit hash: Excludes files containing specific Git commit hashes, identified by the pattern [0-9a-f]{40}.

### write_default_trufflehog_config_if_missing
When set to true, a default .trufflehog3.yml configuration file will be created in the target directory if one does not already exist. Default value is true.

### force_overwrite_trufflehog_config
When set to true, the existing .trufflehog3.yml file in the target directory will be overwritten with the default configuration, even if the file already exists. Default value is false.

### exclude_paths
 A list of paths to be excluded from the Trufflehog3 scan. These paths will be automatically added to the exclusion section of the .trufflehog3.yml configuration file.
The directive add to the .trufflehog3.yml in the repo for scanning new rules. 
```
  - message: Custom Scanio config exclusions
    paths:
      <exclude_paths>
```
Example of using:
```
  exclude_paths: 
    - "vendor"
    - "node_modules"
    - "go.mod"
```
If you use ```write_default_trufflehog_config_if_missing```, ```force_overwrite_trufflehog_config``` together with  ```exclude_paths```, a new config will initially be written. Subsequently, the excluded paths will be added to this new config.

For the further information about the TH3 config file syntax, you may refer to https://github.com/feeltheajf/trufflehog3/blob/master/.trufflehog3.yml 

## New names of scanio metadata files 

The following changes have been made to the naming convention for Scanio metadata files:

### Analyse Metadata Files:
Standard Name: ```ANALYSE_<PLUGIN_NAME>```
CI Mode Name: ```ANALYSE_<PLUGIN_NAME>_<TIMESTAMP>```

### Fetch Metadata Files:
Standard Name: ```FETCH_<PLUGIN_NAME>```
CI Mode Name: ```FETCH_<PLUGIN_NAME>_<TIMESTAMP>```

### VCS Integration Metadata Files:
Standard Name: ```VCS-INTEGRATION_<PLUGIN_NAME>_<ACTION>```
CI Mode Name: ```VCS-INTEGRATION_<PLUGIN_NAME>_<ACTION>_<TIMESTAMP>```

### List Metadata Files:
Standard Name: ```LIST_<PLUGIN_NAME>```
CI Mode Name: ```LIST_<PLUGIN_NAME>_<TIMESTAMP>```

These changes ensure that metadata files are clearly labeled with the plugin name, action (where applicable), and timestamp when in CI mode, enhancing traceability and organization in CI/CD pipelines.

## Updated HTTP Client to Support Custom Headers
The HTTP client used in Scanio has been updated to support custom headers, which can now be configured directly in the orchestrator configuration file. This allows you to add any necessary headers to each HTTP request made by the client.

Example Configuration:
```
http_client:
  custom_headers:                          
    X-Custom-Header: "custom_value"     
```

## Support for Environment Variable Placeholders in the Main Config

The main configuration now supports environment variable placeholders, allowing dynamic values to be injected based on the environment.

Example Configuration:
```
http_client:
  custom_headers:                          
    Authorization: "Bearer ${TOKEN}"     
```

It helps to manage secret values securely via main configuration file.

## Trufflehog3 Report Transformation
- Supported new SARIF and Markdown formats for Trufflehog3 plugin.
```
scanio analyse --scanner trufflehog3 -f markdown /path-to-code/    
scanio analyse --scanner trufflehog3 -f sarif /path-to-code/      
```
- Added functionality allows Trufflehog3 JSON reports to be transformed into SARIF and Markdown formats. If these formats are chosen, the scanner generates a default JSON report, then transforms it into Markdown or SARIF, while preserving the original JSON report.
- Implemented deduplication of scan results for SARIF and Markdown report types.
- Refactored the Trufflehog3 plugin code.

## Other
The ```config_example.yml``` file has been updated to include all new features.

### CODE REVIEW

**Review by japroc — COMMENTED** [review]
I have a question regarding trufflehog3 exclude_paths. Why should individual files like go.mod or pacakge.json be added to an exclude list? For 3rd party code it clear for me, but not for these individual files

**Comment by shikari-ac** [comment]
@japroc 

The basic idea consists of:
- Dependency files contain hashes or similar values that the scanner marks as secrets due to their high entropy. I propose excluding these dependency files because they usually do not contain secrets, while still maintaining high entropy checks at the scanner configuration level.
For example:
```
go.sum
MEDIUM  High Entropy
718  google.golang.org/genproto v0.0.0-20200857031612-b341f8b66230/go.mod h1:jDlOP2FcilWzDD/e9pf2dsT162K34l5v+OpadPcKAAA=
```
- Many repositories lack a ```.trufflehog3.yml``` configuration file. I would like to exclude well-known files on the Scanio end that generate false positives, without requiring repository owners to create the configuration file.

I have also considered other methods, such as:
- Manually providing a configuration file in the TH3 format to Scanio. This would support several cases: adding to an existing config in the repo, rewriting it, or creating a new one if it doesn't exist.
- Supporting the same structure of the TH3 config in the global Scanio config file. Not sure that it's the right place for that. 

I decided to start with the most common scenarios and support only path exclusions without other directives, as many of the configurations can be controlled by scanner flags. JFYI, unfortunately, you cannot add additional configurations to the TH3 scanner using its ```--exclude``` flag; if you use this flag, the .trufflehog3.yml config from the repository will be completely ignored.

If there were a significant number of users who manually need to propagate other directives to the scanner level, we would consider supporting other methods. But for now, I have decided to keep it simple.

**Comment by japroc** [comment]
LGTM

**Review by japroc — APPROVED** [review]
LGTM

**Pull request merged**
